 <div class="container-fluid">
	<div class="row parallax parallax-1" style="background-image: url(/img.php?w=1400&h=800&a=4&c=1&f=/media/parallax/8.jpg);">
		<div class="col-xs-12">
			<h1 class="top">Who is Team</h1>
			<p class="top">Blah Blah BlahBlah Blah BlahBlah Blah BlahBlah Blah BlahBlah Blah BlahBlah Blah BlahBlah Blah BlahBlah Blah BlahBlah Blah BlahBlah Blah BlahBlah Blah BlahBlah Blah BlahBlah Blah BlahBlah Blah BlahBlah Blah Blah</p>
		</div>
	</div>
	<div class="row parallax-2-backdrop" style="background-image: url(/img.php?w=1400&h=800&a=4&c=1&f=/media/parallax/8.jpg);">
		<div class="parallax parallax-2"  style="background-image: url(/img.php?w=1400&h=800&a=4&c=1&f=/media/parallax/8.jpg);">
		</div>
	</div>
	<div class="row white-bg" style="padding-bottom: 40px;padding-top: 40px; background: #fff;">
	</div>
 </div>
 <div class="container-fluid container-sm-height">
	 <div class="row row-sm-height left white-bg">
		<div class="col-xs-12 col-sm-5 col-sm-offset-1 wordage col-sm-height">
			<p>Blah Blah BlahBlah Blah BlahBlah Blah BlahBlah Blah BlahBlah Blah BlahBlah Blah BlahBlah Blah BlahBlah Blah BlahBlah Blah BlahBlah Blah BlahBlah Blah BlahBlah Blah BlahBlah Blah BlahBlah Blah BlahBlah Blah Blah</p>
			<p>
        Blah Blah BlahBlah Blah BlahBlah Blah BlahBlah Blah BlahBlah Blah BlahBlah Blah BlahBlah Blah BlahBlah Blah BlahBlah Blah BlahBlah Blah BlahBlah Blah BlahBlah Blah BlahBlah Blah BlahBlah Blah BlahBlah Blah Blah</p>
		</div>
		<div class="col-xs-12 col-sm-6 wordage white-bg col-sm-height">
			<div class="item" id="team">
				<div class="drop-shadow lifted">
					<img src="/img.php?f=r_fritz_washabaugh_nucleus_development.jpg&w=200" alt="team-fritz"  />
				</div>
				<div class="txt">
					<h3>R. Fritz Washabaugh</h3>
					<h4>Blah blah</h4>
					<h4>Blah blah</h4>
					<h4>blah blah</h4>
				</div>
			</div>
			<br /> <br />
		</div>
	 </div>
</div>
