<div class="container-fluid">
	<div class="row parallax parallax-1" style="background-image: <%parallax-image%>">
		<div class="col-xs-12">
			<h1 class="top">Arch Photo</h1>
			<p class="top">Over the past 15 years, I have seasoned my skills in Architectural and Interior Design photography. Ready for your next shoot?</p>
		</div>
	</div>
  <div class="row parallax-2-backdrop" style="background-image: <%parallax-image%>">
    <div class="parallax parallax-2"  style="background-image: <%parallax-image%>"></div>
  </div>
	<div class="row white-bg">
		<%navsub%>
	</div>
</div>
<div class="container-fluid white-bg">
	<div class="row special">
		<div class="col-xs-12">
		<div id="grid_solve" class="grid_solve model-gallery"></div>
		</div>
	</div>
</div>
