<div class="container-fluid">
	<div class="row parallax parallax-1" style="background-image: <%parallax-image%>">
		<div class="col-xs-12  col-sm-8 col-sm-offset-2">

			<h1 class="top">Works</h1>
			<p class="top">Coding, Development, Photography, and Teaching.</p>

		</div>
	</div>
	<div class="row parallax-2-backdrop" style="background-image: <%parallax-image%>">
    <div class="parallax parallax-2"  style="background-image: <%parallax-image%>">
    </div>
  </div>
	<div class="row white-bg">
		<%navsub%>
	</div>
</div>
<div class="container-fluid white-bg">
	<div class="row">
	<div class="col-xs-12 col-sm-8 col-sm-offset-2" style="padding-bottom: 60px;padding-top: 120px;">
		<h1>Development</h1>
		<p>I started developing websites in high school. That was a long time ago! In that time my pour fingers have built hundreds of websites.
			<br />
			<a href="/works/development">Read more -&gt;</a>
			<br />

		</p>
	</div>
	</div>

	<div class="col-xs-12 col-md-12 wordage" style="padding-bottom: 60px;padding-top: 120px;">
		<h1>Photography</h1>
		<p><em>(We wrote the code that automatically sets up the gallery layout)</em></p>
	</div>
	<div class="row special">
			<div class="col-xs-12">
				<div id="grid_solve" class="grid_solve model-gallery"></div>
			</div>
	</div>


	<div class="col-xs-12 col-md-12 wordage" style="padding-bottom: 60px;padding-top: 120px;">
		<h1>Code</h1>
	</div>
	<div class="row">
			<div class="col-xs-12 col-sm-5 col-sm-offset-1">
				<div id="code" style="background-image: url('/img.php?f=works/code/coding.jpg'); background-repeat: no-repeat; background-size: 150%; height: 40vw"></div>
			</div>
			<div class="col-xs-12 col-sm-4 col-sm-offset-1 wordage left">
				<p>For the past 15 years, I've been programming and have created/published some useful libraries. You are welcome to use them in your projects. Keep in mind the license is still active and works must be attributed to me. Prior permission and approval is required for commercial use. </p>
				<ul>
					<li><a href="/works/coding/mysql-backup">SQL Automated Backup</a></li>
					<li><a href="/works/coding/url-shortener">URL Shortener</a></li>
					<li><a href="/works/coding/zipcode-distance">Zipcode Lookup</a></li>
					<li><a href="/works/coding/prime-number-check">Prime Number Check</a></li>
				</ul>
		<br /><br />
			</div>
	</div>





</div>
