<div class="container-fluid nkdv">
	<div class="row parallax parallax-1" style="background-image: url(/img.php?w=1000&h=600&a=4&c=1&f=/media/parallax/1.jpg);">
		<div class="col-xs-12">
			<h1 class="top nukedev light"><strong>Company</strong><span class="blue">Name</span>  </h1>
			<p class="top">Blah Blah BlahBlah Blah BlahBlah Blah BlahBlah Blah BlahBlah Blah BlahBlah Blah BlahBlah Blah BlahBlah Blah BlahBlah Blah BlahBlah Blah BlahBlah Blah BlahBlah Blah BlahBlah Blah BlahBlah</p>
		</div>
	</div>
  <div class="row parallax-2-backdrop" style="background-image: url(/img.php?w=1000&h=600&a=4&c=1&f=/media/parallax/1.jpg);">
    <div class="parallax parallax-2"  style="background-image: url(/img.php?w=1000&h=600&a=4&&c=1&f=/media/parallax/1.jpg);"></div>
  </div>
  <div class="row dark-tan-bg" style="padding-bottom: 30px;padding-top: 50px;  z-index: 1">
	<div class="col-xs-12 col-sm-8 col-sm-offset-2 wordage" style="padding-bottom: 40px;padding-top: 60px;">
		<h1>Here's Some of Our Work</h1>
		<h4><em>(Development, Photography, Desktop support, &amp; Hosting)</em><br />
			Blah Blah BlahBlah Blah BlahBlah Blah BlahBlah Blah BlahBlah Blah BlahBlah Blah BlahBlah Blah BlahBlah Blah BlahBlah Blah BlahBlah Blah BlahBlah Blah BlahBlah Blah BlahBlah Blah BlahBlah Blah BlahBlah Blah Blah

		</h4>
	</div>
  </div>
	<div class="row blue-light-bg" style="padding-top: 70px; padding-bottom: 70px;">
	  <div class="col-xs-12 col-sm-2 col-sm-offset-1">
	    <div id="usa" class="fade70"></div>
	  </div>

		<div class="col-xs-12 col-sm-8 left">
	    <h3>Made in the USA</h3>
	    <p>Everything we do is made in the USA, in NYC to be exact. We never outsource. Because of our strict policies Quality Control is set to maximum!<br /><br /></p>
	  </div>

		<div class="col-xs-12 col-sm-2 col-sm-offset-1">
	    <div id="durable" class="fade70"></div>
	  </div>

		<div class="col-xs-12 col-sm-8 left">
	    <h3>Security & Analysis</h3>
	    <p>We have a reputation in network Internet security, attack vector analysis, and exploit evaluation and neutralization; with an emphasis in Internet Applications Development.<br /><br /></p>
	  </div>

	<div class="col-xs-12 col-sm-2 col-sm-offset-1">
	    <div id="fast" class="fade70"></div>
	  </div>

	<div class="col-xs-12 col-sm-8 left">
	    <h3>Fast-Loading Responsive Websites</h3>
	    <p>We are geeks and we measure in milliseconds and bits! We optimize everything for speed and compatibility, so our work loads fast!<br /><br /></p>
	  </div>

	</div>
	<div class="row  blue-dark-bg" style="padding-bottom: 120px;padding-top: 80px; z-index: 1">
			  <div class="col-xs-12">
			  	<h2> See More of Our Work</h2>

	</div>

</div>
