<div class="container-fluid">
	<div class="row parallax parallax-1" style="background-image: <%parallax-image%>">
		<div class="col-xs-12">
			<h1 class="top">Database Example</h1>
			<p class="top">This example the current time() stored to the database, and the last 5 records recalled.</p>
		</div>		
	</div>
	<div class="row parallax-2-backdrop" style="background-image: <%parallax-image%>">
	<div class="parallax parallax-2"  style="background-image: <%parallax-image%>"></div>
	</div>
	<div class="row" style="background: #eaeaea;">

	<%navsub%>

	</div>
</div>
<div class="container-fluid white-bg" style="position: relative;">
	<div class="row special" style="background: #eaeaea; padding: 120px;">
		<div class="col-md-12">
			<%code-block%>
		</div>
	</div>
</div>
