<div class="container-fluid">
	<div class="row parallax parallax-1" style="background-image: <%parallax-image%>">
		<div class="col-xs-12">
			<h1 class="top">Auth Example::Create</h1>
			<p class="top">This example auth::create user method.</p>
		</div>		
	</div>
	<div class="row parallax-2-backdrop" style="background-image: <%parallax-image%>">
	<div class="parallax parallax-2"  style="background-image: <%parallax-image%>"></div>
	</div>
	<div class="row" style="background: #eaeaea;">

	<%navsub%>

	</div>
</div>
<div class="container-fluid white-bg" style="position: relative;">
	<div class="row special" style="background: #eaeaea; padding: 120px;">
		<div class="col-md-12">
			<h2>Member Table</h2>
			<%code-block-member%>
			
			<h2>Member Email &amp; Password</h2>
			<%code-block-data%>
		</div>
	</div>
</div>




















