<div class="container-fluid">
	<div class="row parallax parallax-1" style="background-image: <%parallax-image%>"></div>
  <div class="row parallax-2-backdrop" style="background-image: <%parallax-image%>">
    <div class="parallax parallax-2"  style="background-image: <%parallax-image%>"></div>
  </div>
	<div class="row white-bg">
	<%navsub%>
	</div>
</div>
<div class="container-fluid white-bg">
			<%code-block%>
	</div>
