<div class="row">
  <div class="col-xs-12 col-sm-8 col-sm-offset-2 wordage" style="padding-bottom: 30px;padding-top: 120px;">
    <h1>Code Repository :: <%title%></h1>
    <p class="top">
    <em>This code is available for public use. You may copy, distribute, and eat this code as you wish. However, the license remains in effect for the life of the software.</em>
  </div>
</div>
<div class="row">
  <div class="col-xs-12 col-sm-6 col-sm-offset-3 wordage left">
    <p><strong>Pretense for download and use "[Nd] Libraries":</strong><br />
    </p>
    <ul>
      <li>You may not use this code in a commercial setting without prior consent from <a href="mailto:general@domain">domain</a>.</li>
      <li>You may not misrepresent yourself as the author of this code.</li>
      <li>You may make changes to this code, but must make the changes available under this license.</li>
      <li>These libraries are governed by their respective licenses.</li>
    </ul>
  </div>
</div>
<div class="row">
  <div class="col-xs-12 wordage left gray-dark-bg" style="padding-bottom: 60px;padding-top: 120px;">
    <%code_blob%>
  </div>
</div>
