<div class="container-fluid">
	<div class="row parallax parallax-1" style="background-image: <%parallax-image%>">
		<div class="col-xs-12">
			<h1 class="top">Services</h1>
			<p class="top">Blah Blah BlahBlah Blah BlahBlah Blah BlahBlah Blah BlahBlah Blah BlahBlah Blah BlahBlah Blah BlahBlah Blah BlahBlah Blah BlahBlah Blah BlahBlah Blah BlahBlah Blah BlahBlah Blah BlahBlah Blah BlahBlah Blah Blah
</p>
		</div>
	</div>
	<div class="row parallax-2-backdrop" style="background-image: <%parallax-image%>">
		<div class="parallax parallax-2"  style="background-image: <%parallax-image%>">
		</div>
	</div>
	<div class="row" style="padding-bottom: 40px;padding-top: 40px; background: #fff; "></div>
</div>
<div class="container-fluid white-bg">
	<div class="row">
		<div class="col-xs-12 col-md-6 wordage">
				<div class="drop-shadow lifted percent100">
					<img src="/img.php?f=services/design.png&h=500&w=726&c=1" alt="design-pic" />
				</div>
				<h2>Design</h2>
				<h3>Advanced Photoshop &amp; Illustrator skills</h3>
				<p>Blah Blah BlahBlah Blah BlahBlah Blah BlahBlah Blah BlahBlah Blah BlahBlah Blah BlahBlah Blah BlahBlah Blah BlahBlah Blah BlahBlah Blah BlahBlah Blah BlahBlah Blah BlahBlah Blah BlahBlah Blah BlahBlah Blah Blah
<br />
						<br />
<br />
						<br />
</p>
		</div>
		<div class="col-xs-12 col-md-6 wordage">

					<div class="drop-shadow lifted percent100">
						<img src="/img.php?f=services/coding.jpg&h=500&w=726&c=1" alt="develop-pic"  />
					</div>
					<h2>Website Development</h2>
					<h3>Turning Ideas Into Reality</h3>
					<p>Blah Blah BlahBlah Blah BlahBlah Blah BlahBlah Blah BlahBlah Blah BlahBlah Blah BlahBlah Blah BlahBlah Blah BlahBlah Blah BlahBlah Blah BlahBlah Blah BlahBlah Blah BlahBlah Blah BlahBlah Blah BlahBlah Blah Blah
<br />
												<a href="/works/development">See some of the sites we developed</a><br />
						<br />
<br />
						<br />
					</p>
			</div>
			<div class="col-xs-12 col-md-6 wordage">

					<div class="drop-shadow percent100">
						<img src="/img.php?f=home-cards/photo1.jpg&h=500&w=726&c=1" alt="photo-pic"  />
					</div>
					<h2>Photography</h2>
					<h3>Architectural &amp; Design Photography</h3>
					<p>Blah Blah BlahBlah Blah BlahBlah Blah BlahBlah Blah BlahBlah Blah BlahBlah Blah BlahBlah Blah BlahBlah Blah BlahBlah Blah BlahBlah Blah BlahBlah Blah BlahBlah Blah BlahBlah Blah BlahBlah Blah BlahBlah Blah Blah
<br />

						<a href="/works/photography">See some of our work</a><br />
						<br />
<br />
						<br />
					</p>
			</div>
			<div class="col-xs-12 col-md-6 wordage">

					<div class="drop-shadow lifted percent100">
						<img src="/img.php?f=services/hosting.png&h=500&w=726&c=1&a=4" alt="host-pic"  />
					</div>
					<h2>Hosting</h2>
					<h3>Worry-Free Website Hosting</h3>
					<p>Blah Blah BlahBlah Blah BlahBlah Blah BlahBlah Blah BlahBlah Blah BlahBlah Blah BlahBlah Blah BlahBlah Blah BlahBlah Blah BlahBlah Blah BlahBlah Blah BlahBlah Blah BlahBlah Blah BlahBlah Blah BlahBlah Blah Blah
<br />
				<a href="/works/development">See some of the sites we host</a><br />
						<br />
<br />
						<br />
					</p>
			</div>
		</div>
	</div>
</div>
