<div class="container-fluid">
	<div class="row parallax parallax-1" style="background-image: <%parallax-image%>">
		<div class="col-xs-12">
			<h1 class="top">Dev Works</h1>
			<p class="top">I built my first website 1997. I launched my business in web development, when names like Tripod and GeoCites were all the rage.  and it's been nonstop ever since. Check out some the projects we completed recently.</p>
		</div>
	</div>
  <div class="row parallax-2-backdrop" style="background-image: <%parallax-image%>">
    <div class="parallax parallax-2"  style="background-image: <%parallax-image%>"></div>
  </div>
</div>
<div class="container-fluid white-bg">
	<div class="row white-bg">

	<%navsub%>

	</div>
</div>
